### ISSUE TITLE
A next-generation GUI for visualizing big gridded data in Python

### ISSUE THREAD

**Issue by rsignell-usgs** [ESIPFed/GSoC#14] opened 2019-02-11 20:30 UTC
## ESIP Member Organization Name
US Geological Survey

## Mentors
Rich Signell, USGS  @rsignell-usgs 
Martin Durant, Anaconda @martindurant

## Project Idea
[CF-Compliant](http://cfconventions.org/) ndarray datasets can be visualized in tools that understand the [NetCDF Data Model](https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_data_model.html) and the geospatial metadata they contain.   While stand-alone tools like [Panoply](https://www.giss.nasa.gov/tools/panoply/) are often used on the desktop, the goal here is to develop a tool for visualizing and interacting with these datasets in [Jupyter Notebooks](https://jupyter-notebook.readthedocs.io/en/latest/) using [xarray](http://xarray.pydata.org/en/stable/), [dask](http://docs.dask.org/en/latest/) and the [pyviz](http://pyviz.org/) collection of widgets, rendering and layout tools. 

![2019-03-06_15-30-42](https://user-images.githubusercontent.com/1872600/53911596-e23a9080-4024-11e9-8421-c620ee841d91.png)

###  Idea Title 
A next-generation GUI for visualizing big gridded data in Python

#### Abstract
There have been several important advances that now make it possible to render big gridded data from many different sources with a common Python-based toolset in the browser.  The first is the [CF conventions](http://cfconventions.org/) that allow non-ambiguous identification of coordinate and data variables, the second is [xarray](http://xarray.pydata.org/en/stable/) which represents the CF data model in Python, and the third is the [pyviz](http://pyviz.org/) collection of tools, that allows rendering of massive gridded data, widgets to control data selection, and tools to specify layouts of widgets and data displays in the browser.

#### Technical Details

The GSoC student would build a dashboard using panel that allows the user to specify an [intake](https://github.com/ContinuumIO/intake) catalog containing CF-compliant datasets that can be loaded into xarray.   The user would select a dataset, which would then display a list of variables contained in that dataset.  The user would then select a variable, which would then trigger reading the variable by xarray and displaying on a map using [hvplot](https://hvplot.pyviz.org/).    Depending on the variable dimensions, widgets containing time steps and/or vertical levels would be displayed which would allow specification of specific index or coordinate values to plot. 

Bells and whistles like colormap selection and different types of visualization techniques could be added as time permits.   

The work will be coordinated with the overarching "[Next-Generation GUI](https://github.com/ContinuumIO/intake/issues/225)" effort of @martindurant.   

The development can be done on a [Pangeo](pangeo.io) environment running on the Amazon cloud, which means the student will not have run anything or install any software locally -- they will only need their browser and a github account. 

#### Helpful Experience

Experience with Python is required, experience with `xarray`, `pyviz` and `github` a big plus. 

#### First steps

Video:
* [3 minute introduction to Pangeo](https://www.youtube.com/watch?v=rSOJKbfNBNk)
* [20 minute introduction to pyviz](https://www.youtube.com/watch?v=DGLi-UWReM8)
* [3 hour introduction to pyviz](https://www.youtube.com/watch?v=aZ1G_Q7ovmc)
* [40 minute presentation on intake](https://www.youtube.com/watch?time_continue=5&v=PSD7r3JFml0)

Getting Started:
* https://intake.readthedocs.io/en/latest/index.html
* https://panel.pyviz.org
* https://hvplot.pyviz.org/user_guide/index.html
* http://pyviz.org/tutorial/index.html

**Comment by sugam45** [comment] 2019-02-14 12:58
Hi, @rsignell-usgs,
I am very interested in working on the project and making a contribution to it.
Thank You!

**Comment by rsignell-usgs** [comment] 2019-02-14 13:22
@sugam45, excellent.   What is your experience with these components thus far?

**Comment by esip-lab** [comment] 2019-02-14 13:29
Hi all -
Quick reminder that we should hold off on discussing projects at-depth
until February 26th; that is the date mentor organizations are officially
announced. It's okay to say 'hi' though!

AB

Annie Burgess, PhD

Lab Director | Earth Science Information Partners (ESIP)

*esipfed.org/lab <http://esipfed.org/lab>* | 585.738.7549

*Sign up for the monthly ESIP Lab update here <http://eepurl.com/dtKL8z>.*

**Comment by hdsingh** [comment] 2019-02-18 11:48
I got to know about Pyviz through this issue. Pyviz is just absolutely amazing!!! 
It make visualising so much simpler, better and interesting as compared to simply matplotlib, seaborn or other plotting libraries.Thanks a lot for creating this issue and providing such superb resources!!

I would love to contribute to this project for GSOC. I have gone through all the videos mentioned above and finished pyviz tutorials.

There is also personal motivation involved  in this project for me since I have several months of minute stock market data for which I wanted to design a dedicated interactive GUI in Python. This project is very much on the similar lines.

This is the task list I have prepared for myself to get started:
1. Understand `Holoviews` by doing some more similar plotting tasks.
2. Understand internals of `Intake` in depth.
3. Understand `xarray` and `dask` in depth.
4. Start using `Pangeo` to understand it better.
5. Prepare a simple GUI for stock data which will help me to understand `Pyviz` and other packages in much depth and detail.

I really wish that ESIP gets selected!!

**Comment by hdsingh** [comment] 2019-02-27 19:19
Congratulations, ESIP for getting selected in GSOC 2019 !!!

**Comment by rsignell-usgs** [comment] 2019-02-27 20:16
Great news indeed!

**Comment by sugam45** [comment] 2019-02-28 21:53
[pangeo.pydata.org](url) showing the error "Server not found"

**Comment by sugam45** [comment] 2019-02-28 21:54
`[Pangeo ](pangeo.pydata.org)`site showing the error "Server not found"

**Comment by sugam45** [comment] 2019-02-28 21:57
[pangeo.pydata.org](pangeo.pydata.org) site showing the error **"Server Not Found"**. I think they have closed the access to it. 
![screenshot_2019-03-01 deployments pangeo documentation](https://user-images.githubusercontent.com/41995906/53601643-8d38ed80-3bd2-11e9-9e57-e75969c68ec6.png)

**Comment by rsignell-usgs** [comment] 2019-02-28 22:08
Yes, that pangeo instance is gone.    Leaving it wide open was causing the research credits to be depleted too quickly.   You can use the pangeo binder though.  Try clicking the `launch binder` button here, for example: https://github.com/reproducible-notebooks/HRRR_Dashboard

**Comment by kunakl07** [comment] 2019-03-02 21:41
@rsignell-usgs ,I would be thrilled if I get to contribute to this projects as I have done past data visualization projects using Matplotlib,Seaborn,Plotly,Geoplot and also machine learning libraries like sci-kit learn,tensorflow,keras,Categotical Boost and Pybrain

**Comment by veer11997** [comment] 2019-03-04 03:22
i am looking to work on the project of the  organization and contribute to the opensource

**Comment by parthpm** [comment] 2019-03-04 15:06
@rsignell-usgs I am deeply interested in this project.I have done past projects using well known plotting libraries in python.I have gone through the first steps section,Looking forward to contribute.

**Comment by rsignell-usgs** [comment] 2019-03-04 15:42
I'm glad to see all the interest here!   This will be very interesting and rewarding project!

**Comment by kunakl07** [comment] 2019-03-04 15:45
Sir,@rsignell-usgs.Can I contribute to this project?
and where can I find the dataset?
Or should I download the dataset of some regions from NCDC and show you the result?

**Comment by rsignell-usgs** [comment] 2019-03-04 16:02
For reproducibility, better to load data directly from a CF-compliant OPeNDAP endpoint or an S3 bucket (e.g. zarr format), like in:
https://github.com/reproducible-notebooks/HRRR_Dashboard
[![Binder](https://binder.pangeo.io/badge.svg)](https://binder.pangeo.io/v2/gh/reproducible-notebooks/HRRR_Dashboard/master?filepath=HRRR_Dashboard.ipynb)

**Comment by kunakl07** [comment] 2019-03-04 16:12
Thanks sir,@rsignell-usgs!!

**Comment by rsignell-usgs** [comment] 2019-03-05 14:50
Part of this project will be figuring out what the lon,lat and time dimensions of an xarray dataset are, instead of assuming that they are in a certain order, as in the HRRR_Dashboard referenced above.   The MetPy package can do this:
https://stackoverflow.com/questions/53469510/how-to-identify-time-lon-and-lat-coordinates-in-xarray/

**Comment by kunakl07** [comment] 2019-03-06 21:51
Hi @rsignell-usgs ,
With the help of the [link](http://pyviz.org/tutorial/10_Working_with_Large_Datasets.html) that you had provided,I am able to visualize the interactive map.Should,my map also show the latitude and the longitude as the mouse hovers through the region?

**Comment by rsignell-usgs** [comment] 2019-03-06 22:06
Yes, it should as long as the hover control is selected.   Try running this example:
[![Binder](https://binder.pangeo.io/badge.svg)](https://binder.pangeo.io/v2/gh/reproducible-notebooks/HRRR_Dashboard/master?filepath=HRRR_Dashboard.ipynb)
Note also that we currently need conda packages from development channels to make this work:
https://github.com/reproducible-notebooks/HRRR_Dashboard/blob/master/environment.yml

**Comment by kunakl07** [comment] 2019-03-06 22:24
Cool 
Thanks sir
And sir Colab doesn't support pyviz so we need to do in Jupyter Notebook only

**Comment by martindurant** [comment] 2019-03-08 15:12
Signing up to this conversation. I am heading up Intake at Anaconda and involved in our development of the GUI for it.

**Comment by kunakl07** [comment] 2019-03-09 11:44
Hi @rsignell-usgs ,
As the initial task is to predict weather condtions,I have taken weather data from of 5 cities(NCDC).
Here,we are trying to predict the weather for the Danish city "Odense" 24 hours into the future, given the current and past weather-data from 5 cities.
The cities are 'Aalborg', 'Aarhus', 'Esbjerg', 'Odense' and 'Roskilde.
![bandicam 2019-03-09 03-08-52-295](https://user-images.githubusercontent.com/36035718/54071051-9d794a00-421c-11e9-96e6-30e591a634c2.jpg)

I am using a Recurrent Neural Network (RNN) because it can work on sequences of arbitrary length. 
We are going to predict temperature,Pressure and WindSpeed on our test set that the model has never seen during training.
![bandicam 2019-03-09 03-14-19-331](https://user-images.githubusercontent.com/36035718/54071076-cd285200-421c-11e9-8483-a5a528877e22.jpg)

It worked reasonably well for predicting the temperature where the daily oscillations were predicted well, but the peaks were sometimes not predicted so accurately.
![bandicam 2019-03-09 03-14-47-844](https://user-images.githubusercontent.com/36035718/54071099-f77a0f80-421c-11e9-80e8-a0da975f57a0.jpg)

 The atmospheric pressure was also predicted reasonably well, although the predicted signal was more noisy and had a short lag.
 
![bandicam 2019-03-09 03-42-56-922](https://user-images.githubusercontent.com/36035718/54071134-9272e980-421d-11e9-9453-60696f61e860.jpg)

The wind-speed could not be predicted very well,and I think improving dataset would lead to better predictions.
![bandicam 2019-03-09 03-14-56-672](https://user-images.githubusercontent.com/36035718/54071109-21cbcd00-421d-11e9-9629-6f47ee875074.jpg)

**Comment by kunakl07** [comment] 2019-03-09 11:54
@rsignell-usgs ,
Sir,sorry for responding late,the data filtering from NCDC took a lot of my time.
Would the next step be plotting these points on Maps and when we hover the mouse over these co-ordinates it should give us the predicted climate conditions along with longitude and latitude?
Sir,please correct me where I am going wrong and what will be the tasks to be further accomplished.
Thank you.

**Comment by rsignell-usgs** [comment] 2019-03-10 12:32
@kunakl07,  predicting weather via neural nets is cool, but we were intending the focus of this GSoC project to be more on making a general GUI for exploring data n-dimensional data on a map.    

I think a reasonable initial target would be to build off/improve the examples 
https://github.com/reproducible-notebooks/HRRR_Dashboard
https://github.com/reproducible-notebooks/COAWST-ROMS_Dashboards
and try to make the GUI more general, for example, automatically handling a heterogeneous collection of model output such as in the Pangeo Intake catalog:  
https://pangeo.io/catalog.html
https://github.com/pangeo-data/pangeo/raw/master/gce/catalog.yaml
(the zarr datasets in this catalog are publicly readable, but not the netcdf files)

An additional step would be to allow the user to extract and plot a time series at a location selected on the map. 

Does that make sense?

**Comment by kunakl07** [comment] 2019-03-10 14:20
Yes @rsignell-usgs,I got your point.
I was going offtrack and thanks for bringing me back on the right track,now my main focus will be creating a general GUI which can be used to show various dimensions on the map and would start by improving [this](https://github.com/reproducible-notebooks/HRRR_Dashboard).

**Comment by martindurant** [comment] 2019-03-10 15:19
Note for the pangeo Intake catalog linked above: you can also see a nicely rendered version of it at https://pangeo.io/catalog.html .

From the point of view of the visualisation/GUI, you probably need know nothing about the catalog, but I imagine the interface would be passed an xarray object which could come from anywhere. The HRRR Dashboard, above, does not happen to use Intake.

**Comment by kunakl07** [comment] 2019-03-14 17:11
Hi @rsignell-usgs ,
![bandicam 2019-03-14 08-42-01-823](https://user-images.githubusercontent.com/36035718/54375497-5fc25a00-463e-11e9-8f6a-112c5710abec.jpg)
This is the interactive GUI created using holoviews,geoviews,dask,datashader and bokeh of New York Taxi Trip.
When we hover over the image we can see its plot_x and ploy_y's co-ordinates respectively.
The data is loaded in Parquet-format file,Aggregating pickups and dropoffs and then we got hold of xarray arrays and then shaded the region with more drop-offs and pickups
@martindurant ,
<img width="622" alt="Longitude-Latitude" src="https://user-images.githubusercontent.com/36035718/54376569-97ca9c80-4640-11e9-9ff0-91786d048bf7.png">
An interactive GUI that displays latitude and longitude,as we hover over the image.
This is created using only Bokeh and google api wherein we get the latitude and longitude as we hover

If any participant participating in GSOC like me,would require the code for above GUI's,I would be happy to share

**Comment by rsignell-usgs** [comment] 2019-03-18 14:59
Folks, @martindurant and I had a chat and we will be creating a repo with a toy dashboard panel problem that you will be able to work on to show your familiarity with widget interaction.  Should be ready within a few days.

**Comment by rsignell-usgs** [comment] 2019-03-21 06:59
@hdsingh, glad to see you trying to test the Panel GUI progress.   This GSoC project will definitely be harmonized with that work.  

@kunakl07, while the work with the Parquet data is cool, note this GSoC will focus on a GUI for geographic N-dimensional array data (e.g. data that can be loaded in xarray).

**Comment by rsignell-usgs** [comment] 2019-03-21 06:59
Here's the little test problem promised: https://github.com/intake/intake-gsoc-gui

**Comment by martindurant** [comment] 2019-03-21 12:56
Another good and complete example of a Panel-based dashboard is at https://github.com/jsignell/pydata_dc_2018 , notebook 04 - this one actually uses Intake. You can run this example in Binder.

**Comment by hdsingh** [comment] 2019-03-23 15:54
@rsignell-usgs @martindurant I made an interactive dashboard for the test problem [here](https://github.com/intake/intake-gsoc-gui/pull/1).

 Can you please review it and let me know further improvements if any?

**Comment by rsignell-usgs** [comment] 2019-03-23 20:17
@hdsingh , awesome job.  I tried it and it worked great, within the notebook and the standalone app:
![2019-03-23_16-14-59](https://user-images.githubusercontent.com/1872600/54871211-07e6ca00-4d87-11e9-9130-0b42963299ba.png)

**Comment by hdsingh** [comment] 2019-03-24 08:21
@rsignell-usgs Thanks a lot sir!! Glad that you liked it.

**Comment by hdsingh** [comment] 2019-03-25 09:00
I created a new dashboard based on data used in `GUI.ipynb`  in https://github.com/intake/intake/pull/286 . 
The dasboard is available here [Land-Explorer](https://github.com/hdsingh/Land-Explorer).
Here I have shown three differernt methods of generating same dashboard by:
1. Using Holoviews Dynamic Map
2. Using Panel, Streams and Params
3. Using Param

![dashboard](https://user-images.githubusercontent.com/30382331/54906898-4fe22a00-4f0a-11e9-8e2e-9ef17ce1fbe5.png)

**Comment by hdsingh** [comment] 2019-03-25 09:44
I also created a pull request for this dashboard to be merged in intake's GUI.ipynb (https://github.com/intake/intake/pull/308) .

**Comment by rsignell-usgs** [comment] 2019-03-27 12:01
Please submit proposals as soon as possible following [this template](https://github.com/ESIPFed/gsoc/blob/master/STUDENT-proposal-template.md) and remember as stated on the [GSoC proposal information for students]( 
https://google.github.io/gsocguides/student/writing-a-proposal):

> You must create the draft and write an abstract before sharing the draft with the organization.
> You can edit the draft as many times as you wish before the application deadline.

Note the application deadline is April 9 18:00 UTC, but don't wait until then.  Share a draft well before then!

I can be reached via email at rsignell@usgs.gov.

**Comment by hdsingh** [comment] 2019-03-30 08:18
@rsignell-usgs Thanks for the reminder sir. I am working on the proposal. The draft would be ready in a couple of days.

@martindurant  Sir, Can you please share your email address to so that I can also mail you the draft?

**Comment by rsignell-usgs** [comment] 2019-03-30 10:58
@hdsingh , if you share it with me I can share it with Martin.

**Comment by hdsingh** [comment] 2019-04-01 13:20
I just installed and had a look at [ncview](https://anaconda.org/eumetsat/ncview). It must be really very difficult to do research with the help of that tool. Panoply is times better than that. One thing good about ncview is its ability to extract timeseries signal at a particular location. However with the help of Pyviz and intake we can do so much more than just displaying data.

**Comment by rsignell-usgs** [comment] 2019-04-01 13:23
@hdsingh , probably the only functionalities that we could use from ncview (that are not already in panoply) are: 
* extraction of time series, with ability to overlay several time series on same plot
* quick animation of the 2D maps over a specified 3rd dimension (frequently time)

**Comment by martindurant** [comment] 2019-04-01 13:50
@hdsingh : to be sure, there are *many* viewers of particular types of data in particular domains, and it is interesting to consider why some have become ubiquitous and others not, which doesn't necessarily map well to range of functionality. It can be that a viewer has only one feature lacking in others, but the users consider it so important that it compensates for other features being poor or absent. 

For instance, in my former astronomy career, almost all raw image viewing happened in "ds9", which understands world coordinates well, and has a whole host of keyboard-interactive astro tools written for it. 

Meanwhile, my former medical imaging old-guard colleagues were all using imageJ, which has a terrible interface.

Both may be of interest as inspiration/curiosity even when talking geospacial, and we certainly don't want to replicate something that doesn't work well. However, and unfortunately, adoption is much easier had with something that is *familiar* to the community, so you can get further, faster, by not straying too far... Don't forget, that there is always a lot of inertia when people have a tool that they know and gets the job done. It's when they find they can't do anything that they look around for alternatives.

**Comment by hdsingh** [comment] 2019-04-01 18:40
@rsignell-usgs I will figure out a way to implement these functionalities and add these in the proposal.
@martindurant Thank you sir, for your valuable insights. I will design the interface keeping these things in mind. 

The interface would be designed in a way to integrate best features of Panoply and ncview. I will also look into some other softwares available for NetCDF and Geodata visualization and see what are their  features that differentiate them from the others.

**Comment by esip-lab** [comment] 2019-04-02 17:33
Hi all - a friendly reminder that there is ONE WEEK LEFT to submit your proposals for this project! Best of luck and we're excited to see what is submitted!

**Comment by hdsingh** [comment] 2019-04-02 19:19
[Pyviz community ](https://gitter.im/pyviz/pyviz) is really amazing and great !!. Within a few minutes of discussion I got a way to maximise the screen area for the dashboard.

**Comment by rsignell-usgs** [comment] 2019-04-02 20:08
@hdsingh, glad to hear it!

**Comment by hdsingh** [comment] 2019-04-04 10:09
@rsignell-usgs @martindurant I updated my proposal according to our discussion. I also completed the remaining sections and highlighted important improvements. Can you please have a look and let me know what else could be changed?
Thanks a lot!!

**Comment by martindurant** [comment] 2019-04-04 20:35
The proposal is certainly ambitious! I would be very glad to see it all come to fruition.

I promise to have more for you by tomorrow, but a few stylistic initial thoughts:
- you should capitalise all of the names, such as Intake, Python, Panel and so on
- you should provide links for each of these external things (there are many!) the first time it is mentioned outside of abstract. You might consider a glossary section with brief descriptions of all of the components/libraries you refer to.

**Comment by hdsingh** [comment] 2019-04-05 14:48
I modified the proposal according to above recommendations and also added `Time Availability` section. I am waiting to get more feedback.

@rsignell-usgs @martindurant Thanks a lot for the review!

**Comment by martindurant** [comment] 2019-04-05 20:41
I think that the abstract can use a little work, it is the most important part of the proposal.

> have limited functionality and can only be reasonably extended by the software developers on those projects

"limited functionality" is very vague. Rather, you can say that users wish to apply complex analysis methods to the data they are visualising, which is something you can only do in combination with the python-data stack.
Secondly, the latter statement about developers is true for all open-source projects; anyone who contributes to a project is then a developer of that project. I'm not quite sure what you are driving at - is it that you could fairly embed your GUI within other things like Intake's interface, or to use in conjunction with other Python tools like Dask?

> controlled data selection

probably: data-set selection and control of fields for plotting ?

> Currently only stand-alone applications

Is this strictly true? Pangeo is indeed exploring geospatial data in python already, just not as nicely as this GUI would be. You could instead say that the majority of geospatial data visualisation happens in these apps.

> written in Python, but experienced as a dashboard in the browser

"experienced" -> presented
"the browser" -> as a standalone browser app or in a notebook environment

> ..and holds the promise ... explore data

This should be at least two sentences

"Cloud" does not need to be capitalised :)


That's it, good luck!

**Comment by hdsingh** [comment] 2019-04-06 11:32
1. `limited functionality` - resolved
2. `can only be reasonably extended by the software developers on those projects` - Provided example of Dask
3. `controlled data selection` - meant to say different variables, indexes at particular timestamps or locations, so change to `controlled data points selection`
4. All other comments - resolved

I have re-read the Abstract several times so it is becoming a bit difficult for me to approximate the quality of content. Can you please view it one last time before I submit the proposal, just to be sure and let me know?

Thanks a lot!

**Comment by martindurant** [comment] 2019-04-06 19:21
Sorry, I'm travelling today, I probably won't be able to comment any more.

**Comment by hdsingh** [comment] 2019-04-07 18:56
@rsignell-usgs 
I am trying to extract and plot a time series at a location selected on the map using [GreatLakes_Dashboard](https://github.com/reproducible-notebooks/COAWST-ROMS_Dashboards/blob/master/GreatLakes_Dashboard.ipynb)


I extracted the location from map using `streams.Tap`. The location returned is in `lat` and `lon` however dimensions in xarray dataset are `nx`, `ny`. The timeseries could be plotted in relation to `nx ny` by `ds.sel(nx =10,ny = 10,sigma = 0.0).air_u.hvplot()`. However while passing `lat lon` values to `ds.where(((ds.lat==43.5882) & (ds.lon==-77.9989)) ,drop=True)` nothing is returned. I have tested this for multiple values of `lat lon`. 

Can you please give me some more details regarding how to correctly extract time series data w.r.t `lat lon`?

![Screenshot from 2019-04-08 00-17-33](https://user-images.githubusercontent.com/30382331/55688273-62da0d00-5994-11e9-894a-5b4b8bd10f14.png)

**Comment by rsignell-usgs** [comment] 2019-04-07 21:58
@hdsingh, while `xarray` can easily extract a time series at a point when the lat and lon coordinates are one dimensional, when lon and lon coordinates are two dimensional, as in this case, you need to bring in some other tools.   A tree approach is probably best, like: https://stackoverflow.com/a/40044540

**Comment by hdsingh** [comment] 2019-04-08 15:49
Sincere thanks and gratitude to @rsignell-usgs  @martindurant  @jsignell for your guidance  and support during the proposal preparation phase. I feel that because of this project I have learnt so much interesting data visualization things and I am excited to learn more. I have submitted the proposal.
Thanks a lot for listing this project in GSOC!

I am checking out the above approach and let you know soon.

**Comment by hdsingh** [comment] 2019-04-09 14:24
I added a feature to extract time series at a particiular location in [GreatLakes_Dashboard](https://github.com/reproducible-notebooks/COAWST-ROMS_Dashboards/pull/1). I tried `np.unravel_index` based approach first and it seemed to be working fine.

**Comment by rsignell-usgs** [comment] 2019-04-09 14:55
@hdsingh, way to go!  I tried it and it works!   This is really important functionality!

**Comment by hdsingh** [comment] 2019-04-15 03:50
I added a feature to overlay several time series on the same plot in [GreatLakes_Dashboard](https://github.com/reproducible-notebooks/COAWST-ROMS_Dashboards/pull/2). The idea is to replicate the functionality of ncView.

**Comment by rsignell-usgs** [comment] 2019-04-15 13:08
@hdsingh, great!   I love that this is already useful for real work, and will just keep getting more and more useful!
![2019-04-15_9-06-37](https://user-images.githubusercontent.com/1872600/56135033-e039ea80-5f5d-11e9-8f94-f5ee2cb46762.png)

**Comment by hdsingh** [comment] 2019-04-23 10:12
I added [Location Marker](https://github.com/reproducible-notebooks/COAWST-ROMS_Dashboards/pull/3) feature. As of now all the markers are of same color. I will soon update these to have different colors according to time series.

**Comment by rsignell-usgs** [comment] 2019-04-23 13:41
Indeed!   Works great for me:
![2019-04-23_8-47-58](https://user-images.githubusercontent.com/1872600/56585494-ef4b1900-65ab-11e9-9046-b872fc434fd6.jpg)
I'm excited you are continuing to make excellent progress on this!

**Comment by hdsingh** [comment] 2019-04-25 10:42
I added  feature for location markers to have [same color as of their respective time series line](https://github.com/reproducible-notebooks/COAWST-ROMS_Dashboards/pull/5). Please have a look.

**Comment by martindurant** [comment] 2019-04-25 13:29
Thank you @hdsingh !

**Comment by hdsingh** [comment] 2019-05-02 06:14
@rsignell-usgs Sir, Thank you for adding me as a member in the [reproducible-notebooks](https://github.com/reproducible-notebooks) !

**Comment by rsignell-usgs** [comment] 2019-05-02 17:26
@hdsingh, as an experiment, the pyviz team deployed your current Great Lakes notebook as a web app here: https://roms.aip.anaconda.com/GreatLakes_Dashboard.   Very cool!

**Comment by hdsingh** [comment] 2019-05-02 18:12
This is really amazing. I am very glad to see that Pyviz team is also as excited as me for this project!!
Thanks a lot team Pyviz !

**Comment by hdsingh** [comment] 2019-05-06 19:08
@rsignell-usgs @martindurant 
Sir, Thanks a lot for your guidance! I got selected ! 
Looking forward to work and learn more from you.
Let's make this project successful !

**Comment by rsignell-usgs** [comment] 2019-05-06 19:25
Congratulations @hdsingh!   I have no doubt that with your enthusiasm, intelligence and drive, this project will be successful!  This work should have many benefits, among them:
- you will gain through learning and experience
- the community will gain a useful tool for visually exploring CF-compliant multidimensional data
- the community will get a well-documented example of building an interactive daskboard for the browser using Python
- the ESIP Python community will learn more about the power of the PyViz and Intake to aid their scientific workflows

**Comment by martindurant** [comment] 2019-05-06 19:33
Good news - all of the exploratory work has paid off :)

**Comment by ZER-0-NE** [comment] 2019-05-06 19:58
Congratulations @hdsingh :)

**Closed as completed** 2020-01-27 17:16 UTC
Labels: GSoC 2019
